apiVersion: v1
kind: Pod
metadata:
  name: mymulticontainerpod
  labels:
    project: roboshop
    env: dev
    purpose: multi-container-demo
spec:
  containers:
  - name: nginx-container
    image: nginx
  - name: almalinux
    image: almalinux:9
    command: ["sleep","1000"]