apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
  labels:
    project: roboshop
    env: dev
    purpose: resource-limits
spec:
  resources:
    requests:
      memory: "100Mi"
    limits:
      memory: "200Mi"
  containers:
  - name: nginx
    image: nginx
    envFrom:
      - configMapRef:
          name: configmap
      - secretRef:
          name: secret
    
