apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    project: roboshop
    env: dev
    purpose: env
spec:
  containers:
  - name: nginx
    image: nginx
    env:
    - name: COURSE
      value: "kubernates"
    - name: trainer
      value: "siva kumar"
