apiVersion: v1
kind: Pod
metadata:
  name: clusterip
  labels:
    project: roboshop
    env: dev
    purpose: clusterip
spec:
  containers:
  - name: nginx
    image: nginx
---  
apiVersion: v1
kind: Service
metadata: 
  name: nginx
  labels:
    purpose: clusterip
spec:
  selector:
    project: roboshop
    env: dev
    purpose: clusterip
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

