apiVersion: v1
kind: Pod
metadata:
  name: np
  labels:
    project: roboshop
    env: dev
    purpose: np
spec:
  containers:
  - name: nginx
    image: nginx
---  
apiVersion: v1
kind: Service
metadata: 
  name: nginx-np
  labels:
    purpose: nginx-np-demo
spec:
  type: NodePort
  selector:
    project: roboshop
    env: dev
    purpose: np
  ports:
    - protocol: TCP
      port: 80 # service port
      targetPort: 80 # container port

