apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs
  labels:
    name: siddhu
spec:
  replicas: 2
  selector:
   matchLabels:
    project: roboshop
    env: dev
    purpose: rs
  template:
    metadata:
      labels:
        project: roboshop
        env: dev
        purpose: rs
    spec:
      containers:
      - name: nginx
        image: nginx:stable-perl
  
  
